#!/bin/bash

# Check if executing script (wrong!!!)
if [ "$(basename $0)" == "source-me" ]; then
    echo "You should source this script, not run it"
    exit 1
fi

if [[ -z $BITBAKE_ENV ]]; then
# Clone OpenZWave if not done
if [[  -d $HOME/open-zwave ]]; then
    echo "Already cloned."
else
    git clone --depth=1 https://github.com/eiger824/open-zwave.git $HOME/open-zwave
fi

    # Export env variables
    export OZW_ROOT=${HOME}/open-zwave
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OZW_ROOT
else
    # This is a BITBAKE build, then adapt these flags
    # TODO: Fix this, don't hardcode the path
    export OZW_ROOT=${PWD}/../../../openzwave/1.4-r0/git
fi

export OZW_CPP=${OZW_ROOT}/cpp
export OZW_SRC=${OZW_CPP}/src
export OZW_CMD_CLASSES=${OZW_SRC}/command_classes
export OZW_AES=${OZW_SRC}/aes
export OZW_PLATFORM=${OZW_SRC}/platform
export OZW_VALUE_CLASSES=${OZW_SRC}/value_classes
export OZW_SYSCONFDIR=/etc/openzwave


echo "Done."
